# QQQ Top Holdings Configuration
# Top 20% of QQQ constituents by weight (as of 2024)
# These ~20 stocks represent approximately 60-70% of the index

constituents:
  # Top 10 holdings (approximately 50% of index)
  - ticker: AAPL
    name: Apple Inc
    weight: 8.9
    sector: Technology
    
  - ticker: MSFT
    name: Microsoft Corporation
    weight: 8.5
    sector: Technology
    
  - ticker: NVDA
    name: NVIDIA Corporation
    weight: 6.2
    sector: Technology
    
  - ticker: AMZN
    name: Amazon.com Inc
    weight: 5.1
    sector: Consumer Discretionary
    
  - ticker: META
    name: Meta Platforms Inc
    weight: 4.8
    sector: Communication Services
    
  - ticker: AVGO
    name: Broadcom Inc
    weight: 4.5
    sector: Technology
    
  - ticker: GOOGL
    name: Alphabet Inc Class A
    weight: 2.5
    sector: Communication Services
    
  - ticker: GOOG
    name: Alphabet Inc Class C
    weight: 2.4
    sector: Communication Services
    
  - ticker: TSLA
    name: Tesla Inc
    weight: 2.3
    sector: Consumer Discretionary
    
  - ticker: COST
    name: Costco Wholesale Corporation
    weight: 2.1
    sector: Consumer Staples
    
  # Next 10 holdings (approximately 15% of index)
  - ticker: NFLX
    name: Netflix Inc
    weight: 2.0
    sector: Communication Services
    
  - ticker: AMD
    name: Advanced Micro Devices Inc
    weight: 1.9
    sector: Technology
    
  - ticker: PEP
    name: PepsiCo Inc
    weight: 1.5
    sector: Consumer Staples
    
  - ticker: ADBE
    name: Adobe Inc
    weight: 1.4
    sector: Technology
    
  - ticker: CSCO
    name: Cisco Systems Inc
    weight: 1.4
    sector: Technology
    
  - ticker: TMUS
    name: T-Mobile US Inc
    weight: 1.3
    sector: Communication Services
    
  - ticker: INTC
    name: Intel Corporation
    weight: 1.2
    sector: Technology
    
  - ticker: CMCSA
    name: Comcast Corporation
    weight: 1.1
    sector: Communication Services
    
  - ticker: QCOM
    name: QUALCOMM Incorporated
    weight: 1.1
    sector: Technology
    
  - ticker: TXN
    name: Texas Instruments Incorporated
    weight: 1.0
    sector: Technology

# Configuration for data fetching
fetch_config:
  # Options configuration
  strikes_above_atm: 40
  strikes_below_atm: 40
  max_days_to_expiry: 60  # 2 months
  
  # Data fields to fetch for equities
  equity_fields:
    - PX_LAST        # Last price
    - PX_OPEN        # Open price
    - PX_HIGH        # High price
    - PX_LOW         # Low price
    - PX_VOLUME      # Volume
    - VOLUME_AVG_30D # 30-day average volume
    - PX_BID         # Bid price
    - PX_ASK         # Ask price
    - CHG_PCT_1D     # 1-day % change
    - VOLATILITY_30D # 30-day volatility
    - CUR_MKT_CAP    # Market cap
    - PE_RATIO       # P/E ratio
    - DIV_YIELD      # Dividend yield
    
  # Options fields (same as QQQ)
  option_fields:
    - PX_LAST        # Last price
    - PX_BID         # Bid price
    - PX_ASK         # Ask price
    - VOLUME         # Volume
    - OPEN_INT       # Open interest (CRITICAL)
    - IVOL_MID       # Implied volatility
    - DELTA          # Delta
    - GAMMA          # Gamma
    - THETA          # Theta
    - VEGA           # Vega
    - RHO            # Rho
    - OPT_UNDL_PX    # Underlying price
    - BID_SIZE       # Bid size
    - ASK_SIZE       # Ask size

# API usage budgets per constituent
usage_limits:
  max_points_per_ticker: 2000  # Conservative limit per ticker
  daily_budget_allocation: 0.4  # Use 40% of daily limit for constituents
  
# Error handling
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds
  skip_on_error: false  # Continue with next ticker on error
  save_partial_data: true